2024-05-15 14:42:11.180 | INFO     | 12392 | mycroft.messagebus.load_config:load_message_bus_config:33 | Loading message bus configs
2024-05-15 14:42:11.220 | ERROR    | 12392 | mycroft_bus_client.client.client | === OSError(10049, 'L’adresse demandée n’est pas valide dans son contexte', None, 10049, None) ===
Traceback (most recent call last):
  File "C:\ProgramData\miniforge3\envs\phoenix\lib\site-packages\websocket\_app.py", line 312, in run_forever
    self.sock.connect(
  File "C:\ProgramData\miniforge3\envs\phoenix\lib\site-packages\websocket\_core.py", line 249, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "C:\ProgramData\miniforge3\envs\phoenix\lib\site-packages\websocket\_http.py", line 130, in connect
    sock = _open_socket(addrinfo_list, options.sockopt, options.timeout)
  File "C:\ProgramData\miniforge3\envs\phoenix\lib\site-packages\websocket\_http.py", line 200, in _open_socket
    raise error
  File "C:\ProgramData\miniforge3\envs\phoenix\lib\site-packages\websocket\_http.py", line 185, in _open_socket
    sock.connect(address)
OSError: [WinError 10049] L’adresse demandée n’est pas valide dans son contexte
2024-05-15 14:42:11.220 | INFO     | 12392 | mycroft.client.text.text_client:load_settings:189 | Ignoring failed load of settings file
LINES value must be >= 2 and <= 573: got -572
initscr(): Unable to create SP
